# yamllint disable
---
- job:
    name: gitcontrol-test-integration
    parent: ansible-collection-test-integration
    description: |
      Execute ansible-test integration for the collection
    vars:
      ansible_test_test_command: "integration"
      ansible_test_no_temp_unicode: true
    files:
      - ^plugins/module_utils/git.py
      - ^plugins/module_utils/github.py
      - ^plugins/modules/github*
      - ^tests/integration/targets/github*
    pre-run: tests/playbooks/pre.yaml
    secrets:
      - secret: gitcontrol-secret
        name: gitcontrol

- secret:
    name: gitcontrol-secret
    data:
      github_token: !encrypted/pkcs1-oaep
        - nSGFVW6oslgExTSvDPZ2U3hD3zAXJEV53Sw+8KAY/2kPqjmOwsCGwR8SW2XnXTaYQAYa
          Xaz13a/XWljTc74cFkVKLh3UhPkIdxjI5zVvIzCEEn2voZmYHPImiwuCxHp7gle/m0YL
          3uAf+uacL4nS8Yv6lXptJWKMIQzVhrIHjFMVbYQqj+GBDpK+y85U3umftVycfG56xLCU
          OpQM1xnLbX/pO5ToYp/aI6cZO4HTtmAESGwo+U9uSc1yrnm5rTKYoSJGKdsbvudA1m//
          Q66tdMb4mvLmPj4bljTTydC7wyxxFgxnp23EhjylJ+xxewt7di4ABA61bozBcsSs4QxP
          a56uCmM+xTeUZ70iCd4UBUuLz67C+dzmyv6100JVYsfuuwM5I6fOFNvGAYyR1NC3xW/P
          fatXjNcNSM+1+hw8TBmkyNmtaDmk5joSIVjovarq7FFLI4uRN3+LQWfUr/aDv1BrHk5H
          YtOU+13U0xC7vBQb1/gqVribLBa63ZdkKPFRnA6zV2Z5wcP+yUtIzAld6AepCbBPA8Nk
          q2HAXAEcMopxzolQiboobA5tOIRx9K8X6qqN/SdxS31gfOjgsDGUqVnpgP6L5dTEJ9Pj
          I48UXwT3ILlskg8eyH4WXsrEquiFIpTQ8Ymvzf2bNsq11UsP5LxN2hJ3+zZkFXp50pM+
          Sjg=
      gitea_token: !encrypted/pkcs1-oaep
        - XuUP4azy5uo98LW1Z0iDL73XHDkMXzOZA7x3MHtC3nGHZvRdjRJRsYZ76jVAT9RsWPd4
          0RJILFbUv1vcJS57b/oP011fSe89LBMGZHUIBvT/yOWmZ+19h+0rknfPDiKn5d7x9sUr
          yULV9gF+iTDS5D6totatj/RO/iIaogXsMdXASAX927+vbi4fr0rilm99bieGxFAEUHGS
          Z6sebOU97+Piy+Xg6A4PTA7PxqLhUYa4aQT+oe1b4eO0viljS6EYm0WAeZfFRz6pXaIr
          MBN/Xu+XEADCKM0LKiNBBO/9pLCEutjhkvdGtPWET+GecycEMOcOqytAmZuVI73Z37dK
          xsRHd87QX68tW0fwC7gJdpp+4v+KPregmC5JrZxcCbcjbQIjSrrcEnnYxgRWteisjynn
          I39fzEtjyob0twC0ZA9wQjsyyis1Au9SbSFdrXI0tMcYhCiSz1euVBxx0CWe7flTAU4J
          xNxlMS+qSg1R5TPDqMvoyboO58ithoqLPWiwwjXEma+YQn6hjhU2N2jgPNOBCYHkp5Du
          yOiXJi1qhveg20QFrdfeFTgjbZ6pTM49p3vUwHa85Nn/Tmt161Ejx8QbuHU1vPRnWOT9
          JPsfFsIJDt5hs1S22/UU1H5DDXq80C6tiqtIC7XejnqNvgfoc8P5WtHL/AeibvF+3sKG
          A2w=
      gitea_api_url: !encrypted/pkcs1-oaep
        - vaRwLbd6yyckKlhrDQZ4TkD8XD7ISReev68HVOTnwX7tIlSNX4H5TdvWiiiehmEHCXUL
          NN4wfYQ09GfsCXd4QTzjsJLH/hSzO5L4x63hCze3T2Jw3SK70vMSldDmtC9yR2/o3nCp
          cluLAy0F3rRjTwCeLbqNpQfaRbsjCxzrlzMn24/p3QLX5GHxDOyP+lLe4VDxRkQhasr4
          9XRLmRXV+C6hr12f0aLU+FTAZ77kyEo/p3DvFTF9voNtsGgWedslg0NEFrra4778ie8j
          P6XqK/MZMlXxNEZ6LTO8/9xX92JzMpWCEYw0H3QoeTyUvWuKqP9n55qCdsUbDO5ZNg1P
          dOU0VAMSmjs8EbQ0J6W1ajI1JEniw7jdDWCaePSnuwt43Yt9lzNjBX8PG8nFZf5W78Wu
          ZkmZU86ibLoxPkOZc7yD768swzf0cXy1ghSmqAYqaFYnUi2pDMoP8BAZs2YVseTRCPpY
          +Eu8AgbEvCy/SLusVLOPyctEBQvwDGJAU8e1FVKeiTH5zlaf4bxHQD3NQOVXCYDUW5Ii
          ld8xnAGEZRi0LXcfYwOAgZOKA5dOB+mKOIoUHtZkKCzBS+SEOFngrECjEa9Sk5ng4JzX
          Kcw0wmyVM5UxWCab+tu2v4t9GFeb5bbeTUfDgUMM1LhOSZeVKjsAVuTbGvdfEJ4Z24IP
          uRA=

- project:
    merge-mode: squash-merge
    vars:
      ansible_collection_namespace: "opentelekomcloud"
      ansible_collection_name: "gitcontrol"
    check:
      jobs:
        - otc-tox-pep8
        - otc-tox-linters
        - ansible-collection-test-sanity
        - ansible-collection-build
        - ansible-collection-docs
    check-post:
      jobs:
        - gitcontrol-test-integration
    gate:
      jobs:
        - otc-tox-pep8
        - otc-tox-linters
        - ansible-collection-test-sanity
        - ansible-collection-build
        - ansible-collection-docs
        - gitcontrol-test-integration
    release:
      jobs:
        - release-ansible-collection
    promote:
      jobs:
        - promote-ansible-collection-docs
