---
required_status_checks:
  strict: false
  contexts: []
enforce_admins: true
required_pull_request_reviews:
  dismissal_restrictions:
    users: []
    teams: []
  dismiss_stale_reviews: true
  require_code_owner_reviews: false
  required_approving_review_count: 1
who_can_push:
  users: []
  teams: []
  apps: []
required_linear_history: false
allow_force_pushes: false
allow_deletions: false
